name: build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: coady
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        file: ./pylucene/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          coady/pylucene:latest
          coady/pylucene:9
          coady/pylucene:9.10
          coady/pylucene:9.10.0
