name: build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: coady
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        file: ./pylucene/Dockerfile
        push: true
        tags: |
          coady/pylucene:latest
          coady/pylucene:8
          coady/pylucene:8.8
          coady/pylucene:8.8.1
